#!/bin/bash
set -Eeu -o pipefail

if command -v docker &>/dev/null; then
  docker container run \
    --name "calc_$(uuidgen | head -c8)" \
    --rm \
    -it \
    -u "$(id -u):$(id -g)" \
    ghcr.io/shakiyam/calc "$@"
else
  podman container run \
    --name "calc_$(uuidgen | head -c8)" \
    --rm \
    -it \
    ghcr.io/shakiyam/calc "$@"
fi
