#!/bin/bash
set -eu -o pipefail

if [[ $(command -v docker) ]]; then
  docker container run \
    --name calc$$ \
    --rm \
    -it \
    -u "$(id -u):$(id -g)" \
    docker.io/shakiyam/calc "$@"
else
  podman container run \
    --name calc$$ \
    --rm \
    -it \
    docker.io/shakiyam/calc "$@"
fi
