#!/bin/bash
set -eu -o pipefail

if [[ $(command -v docker) ]]; then
  docker container run \
    --name calc_dubug$$ \
    --rm \
    -it \
    -u "$(id -u):$(id -g)" \
    -v "$PWD"/.mypy_cache:/.mypy_cache \
    -v "$PWD"/calc.py:/calc.py:ro \
    docker.io/shakiyam/calc_dev "$@"
else
  podman container run \
    --name calc_dubug$$ \
    --rm \
    --security-opt label=disable \
    -it \
    -v "$PWD"/.mypy_cache:/.mypy_cache \
    -v "$PWD"/calc.py:/calc.py:ro \
    docker.io/shakiyam/calc_dev "$@"
fi
