#!/bin/bash
set -Eeu -o pipefail

# Check if TTY is available
if [ -t 0 ]; then
  TTY_FLAGS="-it"
else
  TTY_FLAGS=""
fi

if command -v docker &>/dev/null; then
  docker container run \
    --name "calc_debug_$(uuidgen | head -c8)" \
    --rm \
    $TTY_FLAGS \
    -u "$(id -u):$(id -g)" \
    -v "$PWD"/.mypy_cache:/opt/calc/.mypy_cache \
    -v "$PWD"/src/calc:/opt/calc/src/calc:ro \
    -v "$PWD"/tests/test_calc.py:/opt/calc/tests/test_calc.py:ro \
    ghcr.io/shakiyam/calc_dev "$@"
else
  podman container run \
    --name "calc_debug_$(uuidgen | head -c8)" \
    --rm \
    --security-opt label=disable \
    $TTY_FLAGS \
    -v "$PWD"/.mypy_cache:/opt/calc/.mypy_cache \
    -v "$PWD"/src/calc:/opt/calc/src/calc:ro \
    -v "$PWD"/tests/test_calc.py:/opt/calc/tests/test_calc.py:ro \
    ghcr.io/shakiyam/calc_dev "$@"
fi
