#!/bin/bash
set -Eeu -o pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
readonly SCRIPT_DIR

if [[ -t 0 ]]; then
  TTY_FLAGS="-t"
else
  TTY_FLAGS=""
fi

if command -v docker &>/dev/null; then
  docker container run \
    --name "calc_dev_$(uuidgen | head -c8)" \
    --rm \
    -i \
    $TTY_FLAGS \
    -u "$(id -u):$(id -g)" \
    -v "$SCRIPT_DIR"/.mypy_cache:/opt/calc/.mypy_cache \
    -v "$SCRIPT_DIR"/pyproject.toml:/opt/calc/pyproject.toml:ro \
    -v "$SCRIPT_DIR"/src/calc:/opt/calc/src/calc:ro \
    -v "$SCRIPT_DIR"/tests:/opt/calc/tests:ro \
    ghcr.io/shakiyam/calc_dev "$@"
else
  podman container run \
    --name "calc_dev_$(uuidgen | head -c8)" \
    --rm \
    --security-opt label=disable \
    -i \
    $TTY_FLAGS \
    -v "$SCRIPT_DIR"/.mypy_cache:/opt/calc/.mypy_cache \
    -v "$SCRIPT_DIR"/pyproject.toml:/opt/calc/pyproject.toml:ro \
    -v "$SCRIPT_DIR"/src/calc:/opt/calc/src/calc:ro \
    -v "$SCRIPT_DIR"/tests:/opt/calc/tests:ro \
    ghcr.io/shakiyam/calc_dev "$@"
fi
