FROM ghcr.io/oracle/oraclelinux:9-slim
COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/uv
# hadolint ignore=DL3041
RUN microdnf -y install python3.12 \
  && microdnf clean all \
  && rm -rf /var/cache
RUN mkdir -p /opt/calc
WORKDIR /opt/calc
COPY requirements_dev.txt .
RUN uv pip install --system --no-cache -r requirements_dev.txt
COPY pyproject.toml .
COPY src ./src
COPY tests ./tests
RUN uv pip install --system --no-cache --no-deps .
ARG SOURCE_COMMIT
ENV SOURCE_COMMIT=$SOURCE_COMMIT
CMD ["/bin/bash"]