name: Check for updates
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  check_for_library_updates:
    name: Check for library updates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run make update_requirements_dev
        run: make update_requirements_dev
      - name: Run check_for_file_updates.sh
        run: ./tools/check_for_file_updates.sh requirements_dev.txt
